version: 2

updates:
- package-ecosystem: npm 
  directory: "/"
  commit-message:
    prefix: "build(pkg)"
  labels:
    - dependencies
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 10

- package-ecosystem: github-actions
  directory: "/"
  commit-message:
    prefix: "ci(deps)"
  labels:
    - dependencies
    - ci 
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 10
