name: Update Reference Documentation

on:
  repository_dispatch:
    types: [update-ref]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-ref:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install tooling
        uses: jdx/mise-action@v2
        with:
          cache: true

      - name: Update discord-luau source
        run: git submodule update --remote --recursive

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV

      - name: Cache pnpm modules
        uses: actions/cache@v5
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Update ref files
        run: mise run generate

      - name: Commit & push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "docs: update refs for https://github.com/DiscordLuau/discord-luau/commit/${{ github.event.client_payload.sha }}" && \
            git push || echo "warn: no changes to commit"

      - name: Deploy dispatch
        uses: peter-evans/repository-dispatch@v4
        with:
          repository: DiscordLuau/docs
          event-type: deploy
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
